source(file = "/home/mads/Documents/phd/publications/molic/R_old/default_graphs.R")
source(file = "/home/mads/Documents/phd/publications/molic/R_old/efs.R")
source(file = "/home/mads/Documents/phd/publications/molic/R_old/efs_utils.R")
source(file = "/home/mads/Documents/phd/publications/molic/R_old/outlier_generics.R")
source(file = "/home/mads/Documents/phd/publications/molic/R_old/outlier_model.R")
source(file = "/home/mads/Documents/phd/publications/molic/R_old/outlier_utils.R")
source(file = "/home/mads/Documents/phd/publications/molic/R_old/rip.R")
