# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

any_true <- function(v) {
    .Call('_molic_any_true', PACKAGE = 'molic', v)
}

pairwise_comb <- function(x) {
    .Call('_molic_pairwise_comb', PACKAGE = 'molic', x)
}

table_count <- function(x) {
    .Call('_molic_table_count', PACKAGE = 'molic', x)
}

matpr <- function(A) {
    .Call('_molic_matpr', PACKAGE = 'molic', A)
}

dfs <- function(adjList, root) {
    .Call('_molic_dfs', PACKAGE = 'molic', adjList, root)
}

#' Minimum Cardinality Search
#' 
#' @param adj A named adjacency list
#' @return A perfect numbering of the nodes
#' @export
mcs <- function(adj) {
    .Call('_molic_mcs', PACKAGE = 'molic', adj)
}

perfect_sequence <- function(adj, z) {
    .Call('_molic_perfect_sequence', PACKAGE = 'molic', adj, z)
}

perfect_cliques <- function(x) {
    .Call('_molic_perfect_cliques', PACKAGE = 'molic', x)
}

perfect_separators <- function(x) {
    .Call('_molic_perfect_separators', PACKAGE = 'molic', x)
}

#' Runnining Intersection Property
#'
#' Given a decomposable graph, this functions finds a perfect numbering on the vertices using maximum cardinality search, and hereafter returns a list with two elements: "C" - A RIP-ordering of the cliques and "S" - A RIP ordering of the separators.
#'
#' @param adj A named adjacency list
#' @export
rip <- function(adj) {
    .Call('_molic_rip', PACKAGE = 'molic', adj)
}

set_intersect <- function(v1, v2) {
    .Call('_molic_set_intersect', PACKAGE = 'molic', v1, v2)
}

set_union <- function(v1, v2) {
    .Call('_molic_set_union', PACKAGE = 'molic', v1, v2)
}

set_diff <- function(v1, v2) {
    .Call('_molic_set_diff', PACKAGE = 'molic', v1, v2)
}

set_eq <- function(v1, v2) {
    .Call('_molic_set_eq', PACKAGE = 'molic', v1, v2)
}

is_subseteq <- function(a, b) {
    .Call('_molic_is_subseteq', PACKAGE = 'molic', a, b)
}

